// src/app/layout.tsx
"use client";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Prompt:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="bg-fixed bg-cover"
        style={{ fontFamily: "Prompt, sans-serif" }}
      >
        <div className="relative z-10">{children}</div>

        {/* Footer */}
        <footer className="footer text-center text-white mt-4">
          <div className="container">
            <p>
              &copy; {new Date().getFullYear()} Dev Tools. All rights
              reserved. | <a href="https://devtools2.vercel.app" target="_blank" rel="noopener noreferrer">Devtools.app</a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export const metadata: Metadata = {
//   title: "Dev | Tools App", // ชื่อของหน้าแอป
//   description: "Generated by create next app", // คำอธิบายของเว็บ
//   icons: {
//     icon: "/logo-grifin.png", // ระบุไอคอนใน public directory
//     apple: "/apple-touch-icon.png", // สำหรับ Apple devices
//   },
//   keywords: ["Next.js", "QR Code", "React"], // คำค้นหา SEO
//   themeColor: "#ffffff", // กำหนดสีพื้นหลังของแถบเบราว์เซอร์
//   viewport: "width=device-width, initial-scale=1", // กำหนด viewport สำหรับ mobile responsiveness
//   openGraph: {
//     title: "Dev | Tools App",
//     description: "Generated by create next app",
//     url: "https://yourwebsite.com",
//     siteName: "Create Next App",
//     images: [
//       {
//         url: "/logo-grifin.png",
//         width: 1200,
//         height: 630,
//       },
//     ],
//     locale: "en_US",
//     type: "website",
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
